service: payency

frameworkVersion: ">=1.2.0 <2.0.0"

plugins:
  - serverless-python-requirements


provider:
  name: aws
  runtime: python3.6
  region: us-west-2  # Oregon

functions:
  currentTime:
    handler: handlers/currentTime.main
    events:
      - http:
          path: time
          method: get
          cors: true

  giveTime:
    handler: handlers/giveTime.main
    events:
      - http:
          path: time
          method: post
          cors: true


              
# This is where we'll create resources like our database table
# resources:
    # Outputs:
      # ApiUrl:
        # Description: "The API Gateway URL"
        # Value:
          # Fn::Join:
            # - ""
            # - - "https://"
              # - Ref: ApiGatewayRestApi
              # - ".execute-api.${self:custom.region}.amazonaws.com/${self:custom.stage}"
#
